name: CI - develop

on:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

    - name: Extract version
      run: |
        echo "IMAGE_VERSION=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

    - name: Lowercase repository name
      run: echo "REPO_NAME=$(echo ${{ github.repository }} | awk '{print tolower($0)}')" >> $GITHUB_OUTPUT

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and publish Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/$REPO_NAME:dev-$IMAGE_VERSION
          ghcr.io/$REPO_NAME:dev-latest