name: CI - main

on:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Extract version
      id: extract_version
      run: |
        echo "version=(jq -r .version package.json)" >> $GITHUB_OUTPUT

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Lowercase repository name
      id: repo_name
      run: echo "repo=$(echo ${{ github.repository }} | awk '{print tolower($0)}')" >> $GITHUB_OUTPUT

    - name: Build and publish Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ steps.repo_name.outputs.repo }}:${{ steps.extract_version.outputs.version }}
          ghcr.io/${{ steps.repo_name.outputs.repo }}:latest