name: CI - develop

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  pre-build:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_NAME: ${{ steps.extract-version.outputs.IMAGE_NAME }}
    steps:
    - name: Lowercase repository name
      run: echo "IMAGE_NAME=$(echo ${{ github.repository }} | awk '{print tolower($0)}')" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: pre-build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and publish Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ needs.pre-build.outputs.IMAGE_NAME }}:dev-${{ inputs.version }}
          ghcr.io/${{ needs.pre-build.outputs.IMAGE_NAME }}:latest