name: CI

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Extract version
      id: extract_version
      run: |
        echo "::set-output name=version::$(jq -r .version package.json)"

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Lowercase repository name
      id: repo_name
      run: echo "::set-output name=repo::$(echo ${{ github.repository }} | awk '{print tolower($0)}')"

    - name: Build and publish Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ghcr.io/${{ steps.repo_name.outputs.repo }}:${{ steps.extract_version.outputs.version }}
          ghcr.io/${{ steps.repo_name.outputs.repo }}:latest